document.createElement("canvas").getContext||function(){function R(){return this.context_||(this.context_=new y(this))}function S(a,b,c){var e=H.call(arguments,2);return function(){return a.apply(b,e.concat(H.call(arguments)))}}function I(a){return(""+a).replace(/&/g,"&amp;").replace(/"/g,"&quot;")}function J(a,b,c){a.namespaces[b]||(7<=T?a.namespaces.add(b,c).doImport("#default#VML"):a.namespaces.add(b,c))}function K(a){J(a,"g_vml_","urn:schemas-microsoft-com:vml");J(a,"g_o_","urn:schemas-microsoft-com:office:office");
a.styleSheets.ex_canvas_||(a=a.createStyleSheet(),a.owningElement.id="ex_canvas_",a.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}")}function U(a){var b=a.srcElement;switch(a.propertyName){case "width":b.getContext().clearRect();b.style.width=b.attributes.width.nodeValue+"px";b.firstChild.style.width=b.clientWidth+"px";break;case "height":b.getContext().clearRect(),b.style.height=b.attributes.height.nodeValue+"px",b.firstChild.style.height=b.clientHeight+
"px"}}function V(a){a=a.srcElement;a.firstChild&&(a.firstChild.style.width=a.clientWidth+"px",a.firstChild.style.height=a.clientHeight+"px")}function z(){return[[1,0,0],[0,1,0],[0,0,1]]}function p(a,b){for(var c=z(),e=0;3>e;e++)for(var g=0;3>g;g++){for(var f=0,d=0;3>d;d++)f+=a[e][d]*b[d][g];c[e][g]=f}return c}function L(a,b){b.fillStyle=a.fillStyle;b.lineCap=a.lineCap;b.lineJoin=a.lineJoin;b.lineWidth=a.lineWidth;b.miterLimit=a.miterLimit;b.shadowBlur=a.shadowBlur;b.shadowColor=a.shadowColor;b.shadowOffsetX=
a.shadowOffsetX;b.shadowOffsetY=a.shadowOffsetY;b.strokeStyle=a.strokeStyle;b.globalAlpha=a.globalAlpha;b.font=a.font;b.textAlign=a.textAlign;b.textBaseline=a.textBaseline;b.arcScaleX_=a.arcScaleX_;b.arcScaleY_=a.arcScaleY_;b.lineScale_=a.lineScale_}function M(a){var b=a.indexOf("(",3),c=a.indexOf(")",b+1),b=a.substring(b+1,c).split(",");if(4!=b.length||"a"!=a.charAt(3))b[3]=1;return b}function A(a,b,c){return Math.min(c,Math.max(b,a))}function B(a,b,c){0>c&&c++;1<c&&c--;return 1>6*c?a+6*(b-a)*c:
1>2*c?b:2>3*c?a+6*(b-a)*(2/3-c):a}function C(a){var b=1,a=""+a;if("#"!=a.charAt(0))if(/^rgb/.test(a)){for(var b=M(a),a="#",c,e=0;3>e;e++)c=-1!=b[e].indexOf("%")?Math.floor(255*(parseFloat(b[e])/100)):+b[e],a+=r[A(c,0,255)];b=+b[3]}else if(/^hsl/.test(a)){e=b=M(a);a=parseFloat(e[0])/360%360;0>a&&a++;c=A(parseFloat(e[1])/100,0,1);e=A(parseFloat(e[2])/100,0,1);if(0==c)c=e=a=e;else{var g=0.5>e?e*(1+c):e+c-e*c,f=2*e-g;c=B(f,g,a+1/3);e=B(f,g,a);a=B(f,g,a-1/3)}a="#"+r[Math.floor(255*c)]+r[Math.floor(255*
e)]+r[Math.floor(255*a)];b=b[3]}else a=W[a]||a;return{color:a,alpha:b}}function X(a){switch(a){case "butt":return"flat";case "round":return"round";default:return"square"}}function y(a){this.m_=z();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=1*n;this.globalAlpha=1;this.font="10px sans-serif";this.textAlign="left";this.textBaseline="alphabetic";this.canvas=a;var b="width:"+a.clientWidth+
"px;height:"+a.clientHeight+"px;overflow:hidden;position:absolute",c=a.ownerDocument.createElement("div");c.style.cssText=b;a.appendChild(c);b=c.cloneNode(!1);b.style.backgroundColor="red";b.style.filter="alpha(opacity=0)";a.appendChild(b);this.element_=c;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}function N(a,b,c,e){a.currentPath_.push({type:"bezierCurveTo",cp1x:b.x,cp1y:b.y,cp2x:c.x,cp2y:c.y,x:e.x,y:e.y});a.currentX_=e.x;a.currentY_=e.y}function O(a,b){var c=C(a.strokeStyle),e=c.color,c=
c.alpha*a.globalAlpha,g=a.lineScale_*a.lineWidth;1>g&&(c*=g);b.push("<g_vml_:stroke",' opacity="',c,'"',' joinstyle="',a.lineJoin,'"',' miterlimit="',a.miterLimit,'"',' endcap="',X(a.lineCap),'"',' weight="',g,'px"',' color="',e,'" />')}function P(a,b,c,e){var g=a.fillStyle,f=a.arcScaleX_,d=a.arcScaleY_,h=e.x-c.x,l=e.y-c.y;if(g instanceof s){var i=0,j=e=0,q=0,k=1;if("gradient"==g.type_){var i=g.x1_/f,c=g.y1_/d,m=a.getCoords_(g.x0_/f,g.y0_/d),i=a.getCoords_(i,c),i=180*Math.atan2(i.x-m.x,i.y-m.y)/Math.PI;
0>i&&(i+=360);1.0E-6>i&&(i=0)}else m=a.getCoords_(g.x0_,g.y0_),e=(m.x-c.x)/h,j=(m.y-c.y)/l,h/=f*n,l/=d*n,k=t.max(h,l),q=2*g.r0_/k,k=2*g.r1_/k-q;f=g.colors_;f.sort(function(a,b){return a.offset-b.offset});for(var d=f.length,m=f[0].color,c=f[d-1].color,h=f[0].alpha*a.globalAlpha,a=f[d-1].alpha*a.globalAlpha,l=[],o=0;o<d;o++){var p=f[o];l.push(p.offset*k+q+" "+p.color)}b.push('<g_vml_:fill type="',g.type_,'"',' method="none" focus="100%"',' color="',m,'"',' color2="',c,'"',' colors="',l.join(","),'"',
' opacity="',a,'"',' g_o_:opacity2="',h,'"',' angle="',i,'"',' focusposition="',e,",",j,'" />')}else g instanceof D?h&&l&&b.push("<g_vml_:fill",' position="',-c.x/h*f*f,",",-c.y/l*d*d,'"',' type="tile"',' src="',g.src_,'" />'):(g=C(a.fillStyle),b.push('<g_vml_:fill color="',g.color,'" opacity="',g.alpha*a.globalAlpha,'" />'))}function v(a,b,c){isFinite(b[0][0])&&isFinite(b[0][1])&&isFinite(b[1][0])&&isFinite(b[1][1])&&isFinite(b[2][0])&&isFinite(b[2][1])&&(a.m_=b,c&&(a.lineScale_=Y(Z(b[0][0]*b[1][1]-
b[0][1]*b[1][0]))))}function s(a){this.type_=a;this.r1_=this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}function D(a,b){if(!a||1!=a.nodeType||"IMG"!=a.tagName)throw new w("TYPE_MISMATCH_ERR");if("complete"!=a.readyState)throw new w("INVALID_STATE_ERR");switch(b){case "repeat":case null:case "":this.repetition_="repeat";break;case "repeat-x":case "repeat-y":case "no-repeat":this.repetition_=b;break;default:throw new w("SYNTAX_ERR");}this.src_=a.src;this.width_=a.width;this.height_=a.height}
function w(a){this.code=this[a];this.message=a+": DOM Exception "+this.code}var t=Math,h=t.round,E=t.sin,F=t.cos,Z=t.abs,Y=t.sqrt,n=10,o=n/2,T=+navigator.userAgent.match(/MSIE ([\d.]+)?/)[1],H=Array.prototype.slice;K(document);var Q={init:function(a){a=a||document;a.createElement("canvas");a.attachEvent("onreadystatechange",S(this.init_,this,a))},init_:function(a){for(var a=a.getElementsByTagName("canvas"),b=0;b<a.length;b++)this.initElement(a[b])},initElement:function(a){if(!a.getContext){a.getContext=
R;K(a.ownerDocument);a.innerHTML="";a.attachEvent("onpropertychange",U);a.attachEvent("onresize",V);var b=a.attributes;b.width&&b.width.specified?a.style.width=b.width.nodeValue+"px":a.width=a.clientWidth;b.height&&b.height.specified?a.style.height=b.height.nodeValue+"px":a.height=a.clientHeight}return a}};Q.init();for(var r=[],d=0;16>d;d++)for(var x=0;16>x;x++)r[16*d+x]=d.toString(16)+x.toString(16);var W={aliceblue:"#F0F8FF",antiquewhite:"#FAEBD7",aquamarine:"#7FFFD4",azure:"#F0FFFF",beige:"#F5F5DC",
bisque:"#FFE4C4",black:"#000000",blanchedalmond:"#FFEBCD",blueviolet:"#8A2BE2",brown:"#A52A2A",burlywood:"#DEB887",cadetblue:"#5F9EA0",chartreuse:"#7FFF00",chocolate:"#D2691E",coral:"#FF7F50",cornflowerblue:"#6495ED",cornsilk:"#FFF8DC",crimson:"#DC143C",cyan:"#00FFFF",darkblue:"#00008B",darkcyan:"#008B8B",darkgoldenrod:"#B8860B",darkgray:"#A9A9A9",darkgreen:"#006400",darkgrey:"#A9A9A9",darkkhaki:"#BDB76B",darkmagenta:"#8B008B",darkolivegreen:"#556B2F",darkorange:"#FF8C00",darkorchid:"#9932CC",darkred:"#8B0000",
darksalmon:"#E9967A",darkseagreen:"#8FBC8F",darkslateblue:"#483D8B",darkslategray:"#2F4F4F",darkslategrey:"#2F4F4F",darkturquoise:"#00CED1",darkviolet:"#9400D3",deeppink:"#FF1493",deepskyblue:"#00BFFF",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1E90FF",firebrick:"#B22222",floralwhite:"#FFFAF0",forestgreen:"#228B22",gainsboro:"#DCDCDC",ghostwhite:"#F8F8FF",gold:"#FFD700",goldenrod:"#DAA520",grey:"#808080",greenyellow:"#ADFF2F",honeydew:"#F0FFF0",hotpink:"#FF69B4",indianred:"#CD5C5C",indigo:"#4B0082",
ivory:"#FFFFF0",khaki:"#F0E68C",lavender:"#E6E6FA",lavenderblush:"#FFF0F5",lawngreen:"#7CFC00",lemonchiffon:"#FFFACD",lightblue:"#ADD8E6",lightcoral:"#F08080",lightcyan:"#E0FFFF",lightgoldenrodyellow:"#FAFAD2",lightgreen:"#90EE90",lightgrey:"#D3D3D3",lightpink:"#FFB6C1",lightsalmon:"#FFA07A",lightseagreen:"#20B2AA",lightskyblue:"#87CEFA",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#B0C4DE",lightyellow:"#FFFFE0",limegreen:"#32CD32",linen:"#FAF0E6",magenta:"#FF00FF",mediumaquamarine:"#66CDAA",
mediumblue:"#0000CD",mediumorchid:"#BA55D3",mediumpurple:"#9370DB",mediumseagreen:"#3CB371",mediumslateblue:"#7B68EE",mediumspringgreen:"#00FA9A",mediumturquoise:"#48D1CC",mediumvioletred:"#C71585",midnightblue:"#191970",mintcream:"#F5FFFA",mistyrose:"#FFE4E1",moccasin:"#FFE4B5",navajowhite:"#FFDEAD",oldlace:"#FDF5E6",olivedrab:"#6B8E23",orange:"#FFA500",orangered:"#FF4500",orchid:"#DA70D6",palegoldenrod:"#EEE8AA",palegreen:"#98FB98",paleturquoise:"#AFEEEE",palevioletred:"#DB7093",papayawhip:"#FFEFD5",
peachpuff:"#FFDAB9",peru:"#CD853F",pink:"#FFC0CB",plum:"#DDA0DD",powderblue:"#B0E0E6",rosybrown:"#BC8F8F",royalblue:"#4169E1",saddlebrown:"#8B4513",salmon:"#FA8072",sandybrown:"#F4A460",seagreen:"#2E8B57",seashell:"#FFF5EE",sienna:"#A0522D",skyblue:"#87CEEB",slateblue:"#6A5ACD",slategray:"#708090",slategrey:"#708090",snow:"#FFFAFA",springgreen:"#00FF7F",steelblue:"#4682B4",tan:"#D2B48C",thistle:"#D8BFD8",tomato:"#FF6347",turquoise:"#40E0D0",violet:"#EE82EE",wheat:"#F5DEB3",whitesmoke:"#F5F5F5",yellowgreen:"#9ACD32"},
G={},d=y.prototype;d.clearRect=function(){this.textMeasureEl_&&(this.textMeasureEl_.removeNode(!0),this.textMeasureEl_=null);this.element_.innerHTML=""};d.beginPath=function(){this.currentPath_=[]};d.moveTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"moveTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};d.lineTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"lineTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};d.bezierCurveTo=function(a,
b,c,e,g,f){g=this.getCoords_(g,f);a=this.getCoords_(a,b);c=this.getCoords_(c,e);N(this,a,c,g)};d.quadraticCurveTo=function(a,b,c,e){a=this.getCoords_(a,b);c=this.getCoords_(c,e);e={x:this.currentX_+2/3*(a.x-this.currentX_),y:this.currentY_+2/3*(a.y-this.currentY_)};N(this,e,{x:e.x+(c.x-this.currentX_)/3,y:e.y+(c.y-this.currentY_)/3},c)};d.arc=function(a,b,c,e,g,f){var c=c*n,d=f?"at":"wa",h=a+F(e)*c-o,l=b+E(e)*c-o,e=a+F(g)*c-o,g=b+E(g)*c-o;h==e&&!f&&(h+=0.125);a=this.getCoords_(a,b);h=this.getCoords_(h,
l);e=this.getCoords_(e,g);this.currentPath_.push({type:d,x:a.x,y:a.y,radius:c,xStart:h.x,yStart:h.y,xEnd:e.x,yEnd:e.y})};d.rect=function(a,b,c,e){this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+e);this.lineTo(a,b+e);this.closePath()};d.strokeRect=function(a,b,c,e){var g=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+e);this.lineTo(a,b+e);this.closePath();this.stroke();this.currentPath_=g};d.fillRect=function(a,b,c,e){var g=this.currentPath_;this.beginPath();
this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+e);this.lineTo(a,b+e);this.closePath();this.fill();this.currentPath_=g};d.createLinearGradient=function(a,b,c,e){var g=new s("gradient");g.x0_=a;g.y0_=b;g.x1_=c;g.y1_=e;return g};d.createRadialGradient=function(a,b,c,e,g,f){var d=new s("gradientradial");d.x0_=a;d.y0_=b;d.r0_=c;d.x1_=e;d.y1_=g;d.r1_=f;return d};d.drawImage=function(a,b){var c,e,d,f,o,u,l,i;d=a.runtimeStyle.width;f=a.runtimeStyle.height;a.runtimeStyle.width="auto";a.runtimeStyle.height=
"auto";var j=a.width,q=a.height;a.runtimeStyle.width=d;a.runtimeStyle.height=f;if(3==arguments.length)c=arguments[1],e=arguments[2],o=u=0,l=d=j,i=f=q;else if(5==arguments.length)c=arguments[1],e=arguments[2],d=arguments[3],f=arguments[4],o=u=0,l=j,i=q;else if(9==arguments.length)o=arguments[1],u=arguments[2],l=arguments[3],i=arguments[4],c=arguments[5],e=arguments[6],d=arguments[7],f=arguments[8];else throw Error("Invalid number of arguments");var k=this.getCoords_(c,e),m=[];m.push(" <g_vml_:group",
' coordsize="',10*n,",",10*n,'"',' coordorigin="0,0"',' style="width:',10,"px;height:",10,"px;position:absolute;");if(1!=this.m_[0][0]||this.m_[0][1]||1!=this.m_[1][1]||this.m_[1][0]){var p=[];p.push("M11=",this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",h(k.x/n),",","Dy=",h(k.y/n),"");var r=this.getCoords_(c+d,e),s=this.getCoords_(c,e+f);c=this.getCoords_(c+d,e+f);k.x=t.max(k.x,r.x,s.x,c.x);k.y=t.max(k.y,r.y,s.y,c.y);m.push("padding:0 ",h(k.x/n),
"px ",h(k.y/n),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",p.join(""),", sizingmethod='clip');")}else m.push("top:",h(k.y/n),"px;left:",h(k.x/n),"px;");m.push(' ">','<g_vml_:image src="',a.src,'"',' style="width:',n*d,"px;"," height:",n*f,'px"',' cropleft="',o/j,'"',' croptop="',u/q,'"',' cropright="',(j-o-l)/j,'"',' cropbottom="',(q-u-i)/q,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",m.join(""))};d.stroke=function(a){var b=[];b.push("<g_vml_:shape",' filled="',
!!a,'"',' style="position:absolute;width:',10,"px;height:",10,'px;"',' coordorigin="0,0"',' coordsize="',10*n,",",10*n,'"',' stroked="',!a,'"',' path="');for(var c={x:null,y:null},e={x:null,y:null},d=0;d<this.currentPath_.length;d++){var f=this.currentPath_[d];switch(f.type){case "moveTo":b.push(" m ",h(f.x),",",h(f.y));break;case "lineTo":b.push(" l ",h(f.x),",",h(f.y));break;case "close":b.push(" x ");f=null;break;case "bezierCurveTo":b.push(" c ",h(f.cp1x),",",h(f.cp1y),",",h(f.cp2x),",",h(f.cp2y),
",",h(f.x),",",h(f.y));break;case "at":case "wa":b.push(" ",f.type," ",h(f.x-this.arcScaleX_*f.radius),",",h(f.y-this.arcScaleY_*f.radius)," ",h(f.x+this.arcScaleX_*f.radius),",",h(f.y+this.arcScaleY_*f.radius)," ",h(f.xStart),",",h(f.yStart)," ",h(f.xEnd),",",h(f.yEnd))}if(f){if(null==c.x||f.x<c.x)c.x=f.x;if(null==e.x||f.x>e.x)e.x=f.x;if(null==c.y||f.y<c.y)c.y=f.y;if(null==e.y||f.y>e.y)e.y=f.y}}b.push(' ">');a?P(this,b,c,e):O(this,b);b.push("</g_vml_:shape>");this.element_.insertAdjacentHTML("beforeEnd",
b.join(""))};d.fill=function(){this.stroke(!0)};d.closePath=function(){this.currentPath_.push({type:"close"})};d.getCoords_=function(a,b){var c=this.m_;return{x:n*(a*c[0][0]+b*c[1][0]+c[2][0])-o,y:n*(a*c[0][1]+b*c[1][1]+c[2][1])-o}};d.save=function(){var a={};L(this,a);this.aStack_.push(a);this.mStack_.push(this.m_);this.m_=p(z(),this.m_)};d.restore=function(){this.aStack_.length&&(L(this.aStack_.pop(),this),this.m_=this.mStack_.pop())};d.translate=function(a,b){v(this,p([[1,0,0],[0,1,0],[a,b,1]],
this.m_),!1)};d.rotate=function(a){var b=F(a),a=E(a);v(this,p([[b,a,0],[-a,b,0],[0,0,1]],this.m_),!1)};d.scale=function(a,b){this.arcScaleX_*=a;this.arcScaleY_*=b;v(this,p([[a,0,0],[0,b,0],[0,0,1]],this.m_),!0)};d.transform=function(a,b,c,e,d,f){v(this,p([[a,b,0],[c,e,0],[d,f,1]],this.m_),!0)};d.setTransform=function(a,b,c,e,d,f){v(this,[[a,b,0],[c,e,0],[d,f,1]],!0)};d.drawText_=function(a,b,c,e,d){var f=this.m_,e=0,o=1E3,p=0,l=[],i;i=this.font;if(G[i])i=G[i];else{var j=document.createElement("div").style;
try{j.font=i}catch(q){}i=G[i]={style:j.fontStyle||"normal",variant:j.fontVariant||"normal",weight:j.fontWeight||"normal",size:j.fontSize||10,family:j.fontFamily||"sans-serif"}}var j=i,k=this.element_;i={};for(var m in j)i[m]=j[m];m=parseFloat(k.currentStyle.fontSize);k=parseFloat(j.size);i.size="number"==typeof j.size?j.size:-1!=j.size.indexOf("px")?k:-1!=j.size.indexOf("em")?m*k:-1!=j.size.indexOf("%")?m/100*k:-1!=j.size.indexOf("pt")?k/0.75:m;i.size*=0.981;m=i.style+" "+i.variant+" "+i.weight+" "+
i.size+"px "+i.family;k=this.element_.currentStyle;j=this.textAlign.toLowerCase();switch(j){case "left":case "center":case "right":break;case "end":j="ltr"==k.direction?"right":"left";break;case "start":j="rtl"==k.direction?"right":"left";break;default:j="left"}switch(this.textBaseline){case "hanging":case "top":p=i.size/1.75;break;case "middle":break;default:case null:case "alphabetic":case "ideographic":case "bottom":p=-i.size/2.25}switch(j){case "right":e=1E3;o=0.05;break;case "center":e=o=500}b=
this.getCoords_(b+0,c+p);l.push('<g_vml_:line from="',-e,' 0" to="',o,' 0.05" ',' coordsize="100 100" coordorigin="0 0"',' filled="',!d,'" stroked="',!!d,'" style="position:absolute;width:1px;height:1px;">');d?O(this,l):P(this,l,{x:-e,y:0},{x:o,y:i.size});d=f[0][0].toFixed(3)+","+f[1][0].toFixed(3)+","+f[0][1].toFixed(3)+","+f[1][1].toFixed(3)+",0,0";b=h(b.x/n)+","+h(b.y/n);l.push('<g_vml_:skew on="t" matrix="',d,'" ',' offset="',b,'" origin="',e,' 0" />','<g_vml_:path textpathok="true" />','<g_vml_:textpath on="true" string="',
I(a),'" style="v-text-align:',j,";font:",I(m),'" /></g_vml_:line>');this.element_.insertAdjacentHTML("beforeEnd",l.join(""))};d.fillText=function(a,b,c,d){this.drawText_(a,b,c,d,!1)};d.strokeText=function(a,b,c,d){this.drawText_(a,b,c,d,!0)};d.measureText=function(a){this.textMeasureEl_||(this.element_.insertAdjacentHTML("beforeEnd",'<span style="position:absolute;top:-20000px;left:0;padding:0;margin:0;border:none;white-space:pre;"></span>'),this.textMeasureEl_=this.element_.lastChild);var b=this.element_.ownerDocument;
this.textMeasureEl_.innerHTML="";this.textMeasureEl_.style.font=this.font;this.textMeasureEl_.appendChild(b.createTextNode(a));return{width:this.textMeasureEl_.offsetWidth}};d.clip=function(){};d.arcTo=function(){};d.createPattern=function(a,b){return new D(a,b)};s.prototype.addColorStop=function(a,b){b=C(b);this.colors_.push({offset:a,color:b.color,alpha:b.alpha})};d=w.prototype=Error();d.INDEX_SIZE_ERR=1;d.DOMSTRING_SIZE_ERR=2;d.HIERARCHY_REQUEST_ERR=3;d.WRONG_DOCUMENT_ERR=4;d.INVALID_CHARACTER_ERR=
5;d.NO_DATA_ALLOWED_ERR=6;d.NO_MODIFICATION_ALLOWED_ERR=7;d.NOT_FOUND_ERR=8;d.NOT_SUPPORTED_ERR=9;d.INUSE_ATTRIBUTE_ERR=10;d.INVALID_STATE_ERR=11;d.SYNTAX_ERR=12;d.INVALID_MODIFICATION_ERR=13;d.NAMESPACE_ERR=14;d.INVALID_ACCESS_ERR=15;d.VALIDATION_ERR=16;d.TYPE_MISMATCH_ERR=17;G_vmlCanvasManager=Q;CanvasRenderingContext2D=y;CanvasGradient=s;CanvasPattern=D;DOMException=w}();
